# This file was generated by Nuitka

# Stubs included by default
from blengine.core import config, logger, storage
from importlib import metadata
import signal
from host import packets, procedures
import blengine
import sys
import os
import subprocess
from bridge import packets
from pathlib import Path
import argparse
from hci import packets, procedures

def _git_infos() -> typing.Any:
    ...
def print_developer_and_version_info() -> typing.Any:
    ...
def keyboardInterruptHandler(signal: typing.Any, frame: typing.Any) -> typing.Any:
    ...
def enable_cli_args(args: typing.Any) -> typing.Any:
    ...

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import signal
import subprocess
import argparse
import pathlib
import importlib
import importlib.metadata
import struct
import time
import pprint
import json
import traceback
import shutil
import blengine.utils.to_bytes
import blengine.utils.parse_str_input_value
import blengine.default_parser
import blengine.enable_cli_args
import webbrowser
import ntpath
import copy
import inspect
import collections
import collections.abc
import blengine.utils.twos_comp
import blengine.utils.twos_comp_invert
import logging
import configobj.ConfigObj
import validate.Validator
import blengine.utils.clone_files_from_git_repo
import queue
import datetime
import threading
import logging.config
import collections.UserList
import concurrent
import concurrent.futures
import difflib
import statistics
import math
import blengine.utils.padortrim
import blengine.utils.bitfield_to_human
import binascii
import enum
import http
import http.client
import hashlib
import ssl
import functools
import re
import intelhex.IntelHex
import blengine.utils.blefloat_to_float
import collections.UserDict
import uuid
import secrets
import serial.to_bytes
import collections.namedtuple
import codecs
import compiler
import ast
import warnings
import socket
import doctest
import _frozen_importlib_external
import abc
import google.protobuf.pyext._message
import google.protobuf.internal._api_implementation
import google._upb._message
import google.protobuf.enable_deterministic_proto_serialization
import pickle
import typing
import io
import weakref
import numbers
import calendar
import encodings
import encodings.raw_unicode_escape
import encodings.unicode_escape
import array
import bisect
import itertools
import collections.deque
import reprlib
import __future__
import ctypes
import ctypes.wintypes
import random